apiVersion: v1
kind: ConfigMap
metadata:
  name: cpusets
  namespace: kube-system
data:
  minikube: |
    nodeName: minikube
    pools:
    - name: gold-pool-1
      cpus: "0-1"
      exclusive: true
    - name: gold-pool-2
      cpus: "2-3"
      exclusive: true
    - name: silver-pool-1
      cpus: "4-5"
      exclusive: false
    - name: silver-pool-2
      cpus: "6-7"
      exclusive: false
  minikube-m02: |
    nodeName: minikube-m02
    pools:
    - name: gold-pool-1
      cpus: "0-3"
      exclusive: true
    - name: silver-pool-1   
      cpus: "4-5"
      exclusive: false
    - name: silver-pool-2
      cpus: "6-7"
      exclusive: false
