apiVersion: batch/v1
kind: Job
metadata:
  name: run-parsec-canneal-gcc-n4-c2-native-5
  labels:
    app: benchmark
    suite: parsec
    benchmark: canneal
    build-config: gcc
    num-threads: "4"
    num-cpus: "2"
    input-size: native
  namespace: benchmarks
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: benchmark
          image: spirals/parsec-3.0
          resources:
            requests:
              "cpu": "1000m"
              "stefanaki.github.com/core": "2"
            limits:
              "cpu": "1000m"
              "stefanaki.github.com/core": "2"
          command:
            - /bin/bash
            - "-c"
            - |
              ./run \
              -a run \
              -p parsec.canneal \
              -c gcc \
              -n 4 \
              -i native && sleep 99999999
  backoffLimit: 4
